image : node:latest

stages:
  - install
  - test
  - deploy

cache :
  paths :
   - node_modules/

install :
 stage : install
 artifacts:
    paths:
      - node_modules/
 script:
  - npm install


test :
  stage : test
  script : 
   - npm run test

production:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=budev --api-key=d2da7495-2783-4633-ba2e-817d155d2dee
  only:
    - ci
