image : node:latest

stages:
  - install
  - test

cache :
  key: ${CI_COMMIT_REF_SLUG}
  paths :
   - node_modules/

install :
 stage : install
 artifacts:
    paths:
      - node_modules/
 script:
  - npm install
 only:
  changes:
    - package-lock.json

test :
  stage : test
  script : 
   - npm run test