image : node:latest

stages:
  - install
  - test

cache :
  paths :
   - node_modules/

install :
 stage : install
 artifacts:
    paths:
      - node_modules/
 script:
  - npm install


test :
  stage : test
  script : 
   - npm run test