image : node:latest

stages:
  - install
  - test

cache :
  paths :
   - node_modules/

install :
 stage : install
 cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
 script:
  - npm ci
 only:
  changes:
    - package-lock.json

test :
  stage : test
  script : 
   - npm run test