image : node:latest

stages:
  # - install
  # - test
  - deploy

# cache :
#   paths :
#    - node_modules/

# install :
#  stage : install
#  artifacts:
#     paths:
#       - node_modules/
#  script:
#   - npm install


# test :
#   stage : test
#   script : 
#    - npm run test

production:
  stage: deploy
  before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass
    - apt-get install -y rsync
  script:
    - export SSHPASS=$PASSWORD
    - sshpass -e ssh -o StrictHostKeyChecking=no -vvv $USER@$$HOSTNAME "echo testing"
    # - sshpass -e ssh -o stricthostkeychecking=no $USER@$HOSTNAME "if cd $CI_PROJECT_NAME; then docker-compose down  && cd .. && rm -rf $CI_PROJECT_NAME; fi && git clone $CI_REPOSITORY_URL && docker build -t tiw5-projetbu ."
    # - sshpass -e ssh -o stricthostkeychecking=no $USER@$HOSTNAME  "cd $CI_PROJECT_NAME  && docker-compose up -d"

  only:
    - deploy
